
## Question 1
Pandas for Data Analysis

In [ ]:

##(a) Data Loading, Datetime Conversion and Feature Extraction

# Import essential libraries
import pandas as pd
import numpy as np


# Load dataset directly from GitHub
url = "https://raw.githubusercontent.com/ek-chris/Practice_datasets/refs/heads/main/eletronic_sales.csv"
df = pd.read_csv(url)



# Convert 'Date' column to datetime format
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# Create new datetime-based columns
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df['Day_of_Week'] = df['Date'].dt.day_name()


display(df[['Date', 'Year', 'Month', 'Day', 'Day_of_Week']].head())



## (b) Branch-Level Total Sales

# Create a new column for Total Sales
df['Total_Sales'] = df['Units'] * df['Price']

# Group by Branch and calculate total sales per branch
branch_sales = agent_sales = (
    df.groupby('Sales Agent', as_index=False)['Total_Sales']
    .sum()
    .sort_values(by='Total_Sales', ascending=False)
)

# Get the top-performing agent
top_agent = agent_sales.iloc[0]

print(f"Agent: {top_agent['Sales Agent']}")
print(f"Total Sales: ${top_agent['Total_Sales']:.2f}")


## (c) Top Performing Sales Agent


# Group by Sales Agent and sum their total sales
agent_sales = (
    df.groupby('Sales Agent', as_index=False)['Total_Sales']
    .sum()
    .sort_values(by='Total_Sales', ascending=False)
)

# Get the top-performing agent
top_agent = agent_sales.iloc[0]

print(f"Agent: {top_agent['Sales Agent']}")
print(f"Total Sales: ${top_agent['Total_Sales']:.2f}")

# Display all agent totals for reference
display(agent_sales)



## (d) Introducing and Filling Missing Values 


# Introduce missing values in Price for rows 5, 15, and 25
df.loc[[5, 15, 25], 'Price'] = np.nan


display(df.loc[[5, 15, 25], ['Products', 'Price']])

# Fill missing values using the median of the Price column
median_price = df['Price'].median()
df['Price'].fillna(median_price, inplace=True)


display(df.loc[[5, 15, 25], ['Products', 'Price']])



# (e) Product-Level Summary 

# Calculate average price and total units sold per product
product_summary = (
    df.groupby('Products', as_index=False)
    .agg(Average_Price=('Price', 'mean'),
         Total_Units_Sold=('Units', 'sum'))
    .sort_values(by='Total_Units_Sold', ascending=False)
)


display(product_summary)

### Question 2
#Numpy for numeric computation

In [ ]:
### Question 2
#Numpy for numeric computation



import numpy as np


## (a) Array Creation and Basic Manipulation 

# Create a NumPy array with 20 random integers between 10 and 100
arr = np.random.randint(10, 101, 20)
print("Original 1D Array (20 random integers between 10 and 100):\n", arr)

# Reshape the array into a 4×5 matrix
arr_reshaped = arr.reshape(4, 5)
print("\n Reshaped Array (4x5 matrix):\n", arr_reshaped)

# Extract the first two rows and last three columns
extracted = arr_reshaped[:2, -3:]
print("\n Extracted Portion (first 2 rows, last 3 columns):\n", extracted)

# Compute the mean and standard deviation of the entire array
mean_val = arr.mean()
std_val = arr.std()
print("\nStatistical Summary:")
print(f"Mean: {mean_val:.2f}")
print(f"Standard Deviation: {std_val:.2f}")

# ------------------------------------------------------------
# (b) Operations on 2D Arrays (6 marks)
# ------------------------------------------------------------

# Simulate a 2D array of students' scores in 5 subjects (10 students)
scores = np.random.randint(40, 101, (10, 5))  # scores between 40 and 100
print("\n Students' Scores (10x5 matrix):\n", scores)

# Calculate the average score per student
avg_per_student = np.mean(scores, axis=1)
print("\n Average Score per Student:\n", avg_per_student)

# Determine the highest and lowest score in the dataset
highest_score = np.max(scores)
lowest_score = np.min(scores)
print("\n Score Summary:")
print(f"Highest Score: {highest_score}")
print(f"Lowest Score: {lowest_score}")





## (c) Working with 3D Arrays 

# Create a 3D array with dimensions (3, 4, 2) filled with random integers between 1 and 20
arr3d = np.random.randint(1, 21, (3, 4, 2))
print("\n 3D Array (3x4x2):\n", arr3d)

# Find the sum of elements across the second axis (axis=1)
sum_across_second_axis = np.sum(arr3d, axis=1)
print("\n Sum of elements across the second axis (axis=1):\n", sum_across_second_axis)

# Compute the maximum value along each layer (axis=0)
max_per_layer = np.max(arr3d, axis=0)
print("\n Maximum value along each layer (axis=0):\n", max_per_layer)

# Flatten the entire 3D array into a 1D array
flattened = arr3d.flatten()
print("\n Flattened 1D Array:\n", flattened)

###  Question 3
# (a) CO₂ Emissions Statistics
Given the dataset of CO₂ emissions (in metric tons per capita) from five countries:  
\[ [25.4, 30.2, 22.5, 28.1, 35.0] \]

We will compute:
- Mean  
- Median  
- Mode  
- Range  
- Standard Deviation  
and provide a brief comment on the data spread.

In [ ]:
##(a) Compute the mean, median, and mode.


import numpy as np
from scipy import stats

# Dataset: CO₂ emissions (metric tons per capita)
co2 = np.array([25.4, 30.2, 22.5, 28.1, 35.0])

# Compute basic statistics
mean_val = np.mean(co2)
median_val = np.median(co2)
mode_val = stats.mode(co2, keepdims=True).mode[0]

## (b) Determine the range and standard deviation
data_range = np.max(co2) - np.min(co2)
std_val = np.std(co2, ddof=1)  # sample std deviation




# Display results
print(f"Mean: {mean_val:.2f}")
print(f"Median: {median_val:.2f}")
print(f"Mode: {mode_val:.2f}")
print(f"Range: {data_range:.2f}")
print(f"Standard Deviation: {std_val:.2f}")

Mean: 28.24
Median: 28.10
Mode: 22.50
Range: 12.50
Standard Deviation: 4.76

### (c) Comment briefly on the spread of the data.

The CO₂ emission values show a **moderate spread**.  
Most countries have emission levels close to the mean, but some variation exists — indicating that emissions differ slightly across countries.

### (b)  Hypothesis Testing
# Hypothesis Testing – Beef Consumption

Two samples of beef consumption (kg/person/year) are given:

- Argentina: [69, 62, 58, 63, 59]  
- Bangladesh: [15, 12, 18, 14, 16]

We will perform a **two-sample t-test** at a 5% significance level (\( \alpha = 0.05 \)) to test if there is a significant difference in mean beef consumption.

In [18]:

## (b)  Hypothesis Testing
# Samples
argentina = np.array([69, 62, 58, 63, 59])
bangladesh = np.array([15, 12, 18, 14, 16])

# Hypotheses:
# H₀: μ₁ = μ₂  (No significant difference)
# H₁: μ₁ ≠ μ₂  (Significant difference exists)

# Perform two-sample t-test
t_stat, p_val = stats.ttest_ind(argentina, bangladesh, equal_var=False)

print(f"T-statistic: {t_stat:.3f}")
print(f"P-value: {p_val}")

# Decision
alpha = 0.05
if p_val < alpha:
    print("Conclusion: Reject H₀ — Significant difference exists between the two countries.")
else:
    print("Conclusion: Fail to reject H₀ — No significant difference found.")

T-statistic: 21.680
P-value: 6.329255804610008e-07
Conclusion: Reject H₀ — Significant difference exists between the two countries.

###  Interpretation:
Since the p-value is much smaller than 0.05, we **reject H₀**.  
This means there **is a statistically significant difference** in average beef consumption between Argentina and Bangladesh.

### (c) Correlation Analysis

Given the following data for **Consumption (x)** and **CO₂ Emission (y)**:  

| Consumption (x) | CO₂ Emission (y) |
|-----------------|------------------|
| 10              | 30               |
| 15              | 45               |
| 20              | 50               |
| 25              | 70               |
| 30              | 85               |

We will compute:
- (a) The Pearson correlation coefficient (r)  
- (b) Interpret the strength and direction of the relationship  
- (c) Explain what it means if \( r \approx 0 \)

In [20]:

##(a) Compute the Pearson correlation coefficient (r) between x and y.

# Given data
x = np.array([10, 15, 20, 25, 30])  # Consumption
y = np.array([30, 45, 50, 70, 85])  # CO₂ emission

# Pearson correlation
corr_coef, p_corr = stats.pearsonr(x, y)

print(f"Pearson Correlation Coefficient: {corr_coef:.3f}")
print(f"P-value: {p_corr:.5f}")

##(b) Interpret the result (comment on the strength and direction of the relationship).


# Interpretation
if corr_coef > 0:
    relation = "positive"
elif corr_coef < 0:
    relation = "negative"
else:
    relation = "no"

print(f"Interpretation: There is a strong {relation} correlation between consumption and CO₂ emissions.")

Pearson Correlation Coefficient: 0.987
P-value: 0.00173
Interpretation: There is a strong positive correlation between consumption and CO₂ emissions.

### (c) Briefly explain what it means if Sr \approx 0$..

If \( r \approx 0 \), it means there is **no linear correlation** between the two variables.  
However, a near-zero value **does not mean there’s no relationship at all** — a **non-linear** association could still exist.

 **In summary:**  
> \( r \approx 0 \Rightarrow \) no linear relationship between \( x \) and \( y \), but possible non-linear connection.

# Question 4 - Linear Algebra

In [28]:
import numpy as np
import pandas as pd

# Define matrix A
A = np.array([
    [80, 70, 90],
    [60, 85, 75],
    [95, 88, 92],
    [70, 60, 65]
], dtype=float)

subjects = ["Math", "English", "Science"]
students = [f"Student_{i+1}" for i in range(A.shape[0])]

# Display A as a DataFrame for clarity
df_A = pd.DataFrame(A, index=students, columns=subjects)
print("Matrix A (student scores):")
display(df_A)


### (a) Total Scores per Student

student_totals = A.sum(axis=1).reshape(-1, 1)  # column vector shape (4,1)
df_totals = pd.DataFrame(student_totals, index=students, columns=["Total"])
print("\n(a) Total scores per student :")
display(df_totals)


### (b) Average Score per Subject

subject_averages = A.mean(axis=0).reshape(1, -1)  # row vector shape (1,3)
df_subject_avg = pd.DataFrame(subject_averages, index=["Average"], columns=subjects)
print("\n(b) Average score per subject :")
display(df_subject_avg)


### (c) Weighted Final Grades
w = np.array([0.5, 0.3, 0.2]).reshape(-1, 1)  # column vector (3,1)
G = A @ w  # result shape (4,1)
df_G = pd.DataFrame(G, index=students, columns=["Weighted_Final_Grade"])
print("\n(c) Weighted final grades:")
display(df_G)


### (d) Applying Subject Importance

# (a) Create A' by multiplying the Math column (first column) by 2
# (b) Recompute totals for each student using A'
A_prime = A.copy()
A_prime[:, 0] = A_prime[:, 0] * 2  # double Math scores

df_A_prime = pd.DataFrame(A_prime, index=students, columns=subjects)
print("\n(d)(a) New matrix A' (Math column multiplied by 2):")
display(df_A_prime)

# Recompute totals
student_totals_prime = A_prime.sum(axis=1).reshape(-1, 1)
df_totals_prime = pd.DataFrame(student_totals_prime, index=students, columns=["New_Total"])
print("\n(d)(b) New total scores per student using A':")
display(df_totals_prime)

# Compare old totals vs new totals
df_compare = pd.concat([df_totals, df_totals_prime], axis=1)
df_compare["Difference"] = df_compare["New_Total"] - df_compare["Total"]
print("\nComparison of totals (Original vs New):")
display(df_compare)

# Brief Explaination
print("\nBrief Explanation:")
print("- Doubling the Math column increases each student's total by exactly their Math score (since Math contribution is doubled).")
print("- Students with higher Math scores see a larger absolute increase in their totals.")
print("- Relative ranking may change if differences in Math scores are large compared to other subjects.")

Matrix A (student scores):

           Math  English  Science
Student_1  80.0     70.0     90.0
Student_2  60.0     85.0     75.0
Student_3  95.0     88.0     92.0
Student_4  70.0     60.0     65.0

(a) Total scores per student :

           Total
Student_1  240.0
Student_2  220.0
Student_3  275.0
Student_4  195.0

(b) Average score per subject :

          Math  English  Science
Average  76.25    75.75     80.5

(c) Weighted final grades:

           Weighted_Final_Grade
Student_1                  79.0
Student_2                  70.5
Student_3                  92.3
Student_4                  66.0

(d)(a) New matrix A' (Math column multiplied by 2):

            Math  English  Science
Student_1  160.0     70.0     90.0
Student_2  120.0     85.0     75.0
Student_3  190.0     88.0     92.0
Student_4  140.0     60.0     65.0

(d)(b) New total scores per student using A':

           New_Total
Student_1      320.0
Student_2      280.0
Student_3      370.0
Student_4      265.0

Comparison of totals (Original vs New):

           Total  New_Total  Difference
Student_1  240.0      320.0        80.0
Student_2  220.0      280.0        60.0
Student_3  275.0      370.0        95.0
Student_4  195.0      265.0        70.0

Brief Explanation:
- Doubling the Math column increases each student's total by exactly their Math score (since Math contribution is doubled).
- Students with higher Math scores see a larger absolute increase in their totals.
- Relative ranking may change if differences in Math scores are large compared to other subjects.